package com.example.data.sheets

import android.util.Log
import com.example.BuildConfig
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import java.util.concurrent.TimeUnit

object GoogleSheetsClient {
    private const val TAG = "GoogleSheetsClient"

    // Base URL is loaded from .env/BuildConfig or falls back gracefully
    private val BASE_URL: String = try {
        // We look for SHEETS_WEB_APP_URL in BuildConfig generated by the plugin
        val rawUrl = BuildConfig.SHEETS_WEB_APP_URL
        if (rawUrl.isNotEmpty() && !rawUrl.contains("placeholder", ignoreCase = true)) {
            Log.d(TAG, "Configuring client with Sheets Web App URL: $rawUrl")
            // Ensure proper trailing slash for Retrofit configuration
            val formattedUrl = if (rawUrl.endsWith("/")) rawUrl else "$rawUrl/"
            // Retrofit base URL must end with '/', let's verify if we need to trim the "/exec" route for base routing
            // Usually Apps Script URL shape: https://script.google.com/macros/s/{DEPLOYMENT_ID}/exec
            // Retrofit base URL should be https://script.google.com/macros/s/{DEPLOYMENT_ID}/ so that path is "exec"
            val cleanBase = if (formattedUrl.endsWith("exec/")) {
                formattedUrl.removeSuffix("exec/")
            } else {
                formattedUrl
            }
            cleanBase
        } else {
            Log.w(TAG, "Sheets Web App URL is a placeholder. Sync will fail gracefully.")
            "https://script.google.com/macros/s/placeholder_sheets_url/"
        }
    } catch (e: Exception) {
        Log.e(TAG, "Failed to load Google Sheets URL: ${e.message}")
        "https://script.google.com/macros/s/placeholder_sheets_url/"
    }

    private val moshi: Moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()

    private val okHttpClient: OkHttpClient by lazy {
        OkHttpClient.Builder()
            .addInterceptor(HttpLoggingInterceptor().apply {
                level = HttpLoggingInterceptor.Level.BODY
            })
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .writeTimeout(30, TimeUnit.SECONDS)
            .build()
    }

    val apiService: SheetsApiService by lazy {
        Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(okHttpClient)
            .addConverterFactory(MoshiConverterFactory.create(moshi))
            .build()
            .create(SheetsApiService::class.java)
    }

    /**
     * Helper to verify if dynamic sync endpoint is accurately populated.
     */
    val isConfigured: Boolean
        get() = !BASE_URL.contains("placeholder")
}
